### ISSUE TITLE
ValueError: API 'QDate' has already been set to version 1

### ISSUE THREAD

**Issue by bl4k1st** [g1itch/PyBitmessage#3]
I constantly get the following error:

`Loading existing config files from /root/.config/PyBitmessage/
Using default logger configuration
2018-10-09 14:26:55,215 - ERROR - /root/.namecoin/namecoin.conf unreadable or missing, Namecoin support deactivated
2018-10-09 14:26:55,368 - CRITICAL - Unhandled exception
Traceback (most recent call last):
  File "bitmessagemain.py", line 434, in <module>
    main()
  File "bitmessagemain.py", line 431, in main
    mainprogram.start()
  File "bitmessagemain.py", line 333, in start
    bitmessageqt.run()
  File "/root/PROGRAMS/PyBitmessage-0.6.3.2/src/bitmessageqt/__init__.py", line 4403, in run
    myapp = MyForm()
  File "/root/PROGRAMS/PyBitmessage-0.6.3.2/src/bitmessageqt/__init__.py", line 579, in __init__
    self.ui.setupUi(self)
  File "/root/PROGRAMS/PyBitmessage-0.6.3.2/src/bitmessageqt/bitmessageui.py", line 559, in setupUi
    self.blackwhitelist = Blacklist()
  File "/root/PROGRAMS/PyBitmessage-0.6.3.2/src/bitmessageqt/blacklist.py", line 17, in __init__
    widgets.load('blacklist.ui', self)
  File "/root/PROGRAMS/PyBitmessage-0.6.3.2/src/bitmessageqt/widgets.py", line 13, in load
    uic.loadUi(resource_path(resFile), widget)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 236, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/loader.py", line 50, in __init__
    UIParser.__init__(self, QtCore, QtGui, LoaderCreatorPolicy(package))
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 183, in __init__
    self.factory = QObjectCreator(creatorPolicy)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/objcreator.py", line 94, in __init__
    modinfo = plugin_locals["moduleInformation"]()
  File "<string>", line 52, in moduleInformation
  File "/usr/lib/python2.7/dist-packages/qgis/__init__.py", line 26, in <module>
    from qgis.PyQt import QtCore
  File "/usr/lib/python2.7/dist-packages/qgis/PyQt/QtCore.py", line 28, in <module>
    sip.setapi(api, 2)
ValueError: API 'QDate' has already been set to version 1`

**Comment by g1itch** [comment]
Please use formatting. It's hard to read. The issues in my PyBitmessage fork is for my branches like `ui-refactoring` or `qt5-wip`. It seems you are using `v0.6`, so it's irrelevant here ):
